spring:
  application:
    name: input-demo
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.6.150:9092
      bindings:
        input:
          destination: cfn
          group: cfn
      instance-count: 2
      instance-index: 0
