spring:
  application:
    name: spring-cloud-consumers
  boot:
    admin:
      client:
        url: http://localhost:8769
  main:
    allow-bean-definition-overriding: on
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.6.150:9092
          auto-add-partitions: true
          auto-create-topics: true
      bindings:
        input:
          destination: new2
          group: input-group-2
          consumer:
            autoCommitOffset: false
            concurrency: 1
            partitioned: true
      #instance-count: 2

server:
  port: 8763
  servlet:
    context-path: / #访问路径
eureka:
  instance: #实例
    prefer-ip-address: on #是否使用IP地址进行访问
    #实例显示名
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
      #拉服务列表时间间隔

#logging:
#  level:
#    root: Debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


ribbon:
  ServerListRefreshInterval: 5000
  ConnectTimeout: 500
  ReadTimeout: 2000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
feign:
  hystrix:
    enabled: on
