spring:
  application:
    name: gateway-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
server:
  port: 8080