server:
  port: 8764

spring:
  application:
    name: app-eureka-center
  security:
    basic:
      enabled: true
    user:
      name: user
      password: password123

eureka:
  instance:
    hostname: server1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:password123@server:8761/eureka/