server:
  port: 8761

spring:
  application:
    name: app-eureka-center
  security:
    basic:
      enabled: true               # 开启基于HTTP basic的认证
    user:
      name: user                  # 配置登录的账号是user
      password: password123       # 配置登录的密码是password123

eureka:
  server:
    # 禁用Eureka的ReadOnlyMap缓存 (Eureka端)
    use-read-only-response-cache: false
    #启用主动失效，并且每次主动失效检测间隔为3s (Eureka端)
    eviction-interval-timer-in-ms: 3000
  instance:
    hostname: server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server:8761/eureka/
debug: true