spring:
  application:
    name: eureka-provider #服务名

server:
  port: 8762 #服务访问端口
  servlet:
    context-path: / #访问路径
eureka:
  instance: #Eureka 实例
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    leaseRenewalIntervalInSeconds: 5
    health-check-url-path: /actuator/health
    #是否使用IP地址进行访问
    prefer-ip-address: on
    #实例显示名
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    #服务过期时间
    lease-expiration-duration-in-seconds: 15
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
debug: on