server:
  port: 8763
  servlet:
    context-path: / #访问路径
spring:
  application:
    name: spring-cloud-consumers
  main:
    allow-bean-definition-overriding: true
eureka:
  instance: #实例
    prefer-ip-address: true #是否使用IP地址进行访问
    #实例显示名
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/

